---
title: "Genome Length"
output: pdf_document
---

```{r Load the Data, echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(ggplot2)
library(ggplot2bdc)
library(Hmisc)

load(file='../data/gnhdata.rda')
source('gnh_summary.R')
source('gnh_labels.R')

struct_labeler <- function(variable, value)
{
    labels <- c('lattice, 25x25'='Structured',
                'well-mixed, 625'='Unstructured')
    return(labels[value])
}

```

# Proportion of Producers for diferent genome lengths

## Genome Lengths 0 and 8

This plot demonstrates that adaptation to non-social traits can significantly increase the amount of time that producers are present.

```{r Proportion of Producers - Main, fig.cap='Proportion of producers over time when adaptation to stress is possible (L=8) and not (L=0). Shaded areas indicate bootstrapped 95% confidence intervals.'}
gldata_08 <- gnhdata %>%
    filter(GenomeLength==0 | GenomeLength==8) %>%
    filter(SocialMutations==TRUE) %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MinCarryingCapacity==800 & MaxCarryingCapacity==2000) %>%
    filter(MigrationRate==0.05) %>%
    filter(MutationRateSocial==1e-5 & MutationRateAdaptation==1e-5) %>%
    filter(MutationRateStress==1e-5) %>%
    group_by(Time, GenomeLength, PopulationStructure) %>%
    do(gnh_summary(.$MeanProducerProportion))

p_gl08 <- ggplot(gldata_08, aes(x=Time, y=Mean, color=as.factor(GenomeLength),
              fill=as.factor(GenomeLength), linetype=PopulationStructure)) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    scale_color_hue(name=label_genome_length, guide=guide_legend(order=1, keywidth=0.9)) +
    scale_fill_hue(guide=FALSE) +
    scale_linetype_manual(values=c('lattice, 25x25'='solid',
                                   'well-mixed, 625'='dashed'),
                          labels=c('lattice, 25x25'='Structured',
                                   'well-mixed, 625'='Unstructured'),
                          name='Metapopulation Structure',
                          guide=guide_legend(order=2, keywidth=0.9)) +
    labs(x=label_time, y=label_producer_proportion) +
    theme_bdc_grey()
rescale_golden(p_gl08)
# ggsave_golden('../figures//08-spatial_vs_non-producer_proportion.png')
```

### All Genome Lengths (0-10)

```{r Proportion of Producers - Full, fig.cap='Proportion of producers over time for different genome lengths in structured and unstructured populations. Shaded areas indicate bootstrapped 95% confidence intervals.'}
gldata_all <- gnhdata %>%
    filter(SocialMutations==TRUE) %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MinCarryingCapacity==800 & MaxCarryingCapacity==2000) %>%
    filter(MigrationRate==0.05) %>%
    filter(MutationRateSocial==1e-5 & MutationRateAdaptation==1e-5 & MutationRateStress==1e-5) %>%
    group_by(Time, GenomeLength, PopulationStructure) %>%
    do(gnh_summary(.$MeanProducerProportion))

p_glall <- ggplot(gldata_all, aes(x=Time, y=Mean, color=as.factor(GenomeLength),
              fill=as.factor(GenomeLength), linetype=PopulationStructure)) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    scale_linetype_manual(values=c('lattice, 25x25'='solid',
                                   'well-mixed, 625'='dashed'),
                          name='Metapopulation Structure', guide=FALSE) +
    scale_color_hue(name=label_genome_length, guide=guide_legend(order=1)) +
    scale_fill_hue(guide=FALSE) +
    facet_grid(PopulationStructure ~ ., labeller=struct_labeler) +
    labs(x=label_time, y=label_producer_proportion) +
    theme_bdc_grey()
rescale_plot(p_glall, ratio=2.5)
# ggsave(filename='../figures/all-spatial_vs_non-producer_proportion.png')
```


# Producer "Presence" (Integral)

```{r Producer Presence - Subsetting the Data}

prod_integrals <- gnhdata %>%
    filter(SocialMutations==TRUE) %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MinCarryingCapacity==800 & MaxCarryingCapacity==2000) %>%
    filter(MigrationRate==0.05) %>%
    filter(MutationRateSocial==1e-5 & MutationRateAdaptation==1e-5) %>%
    filter(MutationRateStress==1e-5) %>%
    #select(Time, MeanProducerProportion, GenomeLength, PopulationStructure, Replicate) %>%
    group_by(GenomeLength, PopulationStructure, Source, Replicate) %>%
    summarise(Integral=sum(MeanProducerProportion))

prod_integrals08 <- filter(prod_integrals, GenomeLength==0 | GenomeLength==8)
```

Hello.

```{r Producer Presence - Main, fig.cap='Producer presence (integral) over 2990 cycles in structured (lattice) and unstructured environments. Error bars indicate bootstrapped 95% confidence intervals.'}

p <- ggplot(prod_integrals08, aes(x=as.factor(GenomeLength), y=Integral,
                                  color=PopulationStructure,
                                  shape=PopulationStructure)) +
    #geom_point(shape=1, alpha=0.1) +
    stat_summary(fun.y='mean', geom='line', aes(group=PopulationStructure)) +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_discrete(breaks=unique(prod_integrals08$GenomeLength)) +
    scale_color_hue(name='Metapopulation Structure', labels=c("lattice, 25x25"="Structured",
                                                          "well-mixed, 625"="Unstructured"),
                    guide=guide_legend(order=1)) +
    scale_shape_manual(name='Metapopulation Structure',
                       labels=c("lattice, 25x25"="Structured",
                                "well-mixed, 625"="Unstructured"),
                       values=c("lattice, 25x25"=15,
                                "well-mixed, 625"=16), guide=guide_legend(order=1)) +
    labs(x=label_genome_length, y=sprintf('Producer Presence over %d Cycles', max(gnhdata$Time)-min(gnhdata$Time))) +
    theme_bdc_grey(grid.y=FALSE)
rescale_plot(p, ratio=0.2)
# ggsave('../figures//08-spatial_vs_non-producer_presence.png')
```


```{r Producer Presence - Main Regression}
structured <- filter(prod_integrals08, PopulationStructure=='lattice, 25x25')
unstructured <- filter(prod_integrals08, PopulationStructure=='well-mixed, 625')

structured_lm <- lm(Integral~GenomeLength, data=structured)
unstructured_lm <- lm(Integral~GenomeLength, data=unstructured)

summary(structured_lm)
summary(unstructured_lm)
```


```{r Producer Presence - Full, fig.cap='Producer presence (integral) over 2990 cycles in structured (lattice) and unstructured environments. Error bars indicate bootstrapped 95% confidence intervals.'}
p <- ggplot(prod_integrals, aes(x=GenomeLength, y=Integral,
                                color=PopulationStructure,
                                shape=PopulationStructure)) +
    #geom_point(shape=1, alpha=0.1) +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_continuous(breaks=unique(prod_integrals$GenomeLength)) +
    scale_color_hue(name='Metapopulation Structure',
                    labels=c("lattice, 25x25"="Structured",
                             "well-mixed, 625"="Unstructured"),
                    guide=guide_legend(order=1, keywidth=0.9)) +
    scale_shape_manual(name='Metapopulation Structure',
                       labels=c("lattice, 25x25"="Structured",
                                "well-mixed, 625"="Unstructured"),
                       values=c("lattice, 25x25"=15,
                                "well-mixed, 625"=16),
                       guide=guide_legend(order=1, keywidth=0.9)) +
    labs(x=label_genome_length,
         y=sprintf('Producer Presence over %d Cycles',
                   max(gnhdata$Time)-min(gnhdata$Time))) +
    theme_bdc_grey(grid.y=FALSE)
rescale_golden(p)
# ggsave_golden('../figures/all-spatial_vs_non-producer_presence.png')
```
