---
title: "Migration Rate"
output: html_document
---

```{r Load the Data, echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(ggplot2)
library(ggplot2bdc)
library(Hmisc)

load(file='../data/gnhdata.rda')
source('gnh_summary.R')

struct_labeler <- function(variable, value)
{
    labels <- c('lattice, 25x25'='Structured',
                'well-mixed, 625'='Unstructured')
    return(labels[value])
}

migration_labels <- c('5e-7'='0.0000005', '5e-6'='0.000005', '5e-5'='0.00005',
                      '5e-4'='0.0005', '5e-3'='0.005', '5e-2'='0.05',
                      '5e-1'='0.5')

migration_labels_f <- c('5e-7'='0.0000005', '5e-6'='0.000005', '5e-5'='0.00005',
                      '5e-4'='0.0005', '5e-3'='0.005', '5e-2'='0.05',
                      '5e-1'='0.5')
```

```{r chunk1}
migration_data <- gnhdata %>%
    filter(GenomeLength==8) %>%
    filter(PopulationStructure=='lattice, 25x25') %>%
    filter(SocialMutations==TRUE) %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MinCarryingCapacity==800 & MaxCarryingCapacity==2000) %>%
    filter(MutationRateSocial==1e-5 & MutationRateAdaptation==1e-5 & MutationRateStress==1e-5) %>%
    group_by(Time, MigrationRate) %>%
    do(gnh_summary(.$MeanProducerProportion))

p_proportion <- ggplot(migration_data, aes(x=Time, y=Mean, color=as.factor(MigrationRate),
              fill=as.factor(MigrationRate))) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    scale_color_hue(name='Migration Rate (m)', guide=guide_legend(order=1)) +
    scale_fill_hue(guide=FALSE) +
    labs(x='Time (T)', y='Producer Proportion') +
    theme_bdc_grey()
rescale_golden(p_proportion)
# ggsave_golden('../figures//all-migration-proportion.png')
```


```{r chunk2}
migration_integrals <- gnhdata %>%
    filter(GenomeLength==8) %>%
    filter(SocialMutations==TRUE) %>%
    filter(PopulationStructure=='lattice, 25x25') %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MutationRateSocial==1e-5 & MutationRateAdaptation==1e-5 & MutationRateStress==1e-5) %>%
    filter(MinCarryingCapacity==800 & MaxCarryingCapacity==2000) %>%
    group_by(MigrationRate, Replicate, Source) %>%
    summarise(Integral=sum(MeanProducerProportion))

p_presence <- ggplot(migration_integrals, aes(x=MigrationRate, y=Integral)) +
    geom_point(shape=1, alpha=0.06, position='identity') +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_log10(breaks=unique(migration_integrals$MigrationRate),
                  labels=migration_labels) +
    labs(x='Migration Rate (m)',
         y=sprintf('Producer Presence over %d Cycles',
                   max(gnhdata$Time)-min(gnhdata$Time))) +
    theme_bdc_grey(grid.y=FALSE)
rescale_golden(p_presence)
# ggsave_golden('../figures//all-migration-presence.png')
```
