---
title: "Social Mutations"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
library(ggplot2bdc)
library(Hmisc)
library(magrittr)

load(file='../data/gnhdata.rda')
source('gnh_summary.R')
source('gnh_labels.R')

smu_labeller <- function(variable, value)                                     
{                                                                               
    labels <- c('1e-05'=expression(bold('0.00001')),                
                '0'='0')                               
    return(labels[as.character(value)])                                                       
}

```

```{r subsetting}
social_data <- gnhdata %>%
    filter(PopulationStructure=='lattice, 25x25') %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MigrationRate==0.05) %>%
    filter(MutationRateAdaptation==1e-5) %>%
    filter(MutationRateStress==1e-5) %>%
    filter(MinCarryingCapacity==800) %>%
    filter(MaxCarryingCapacity==2000)
```

```{r analysis}
social_prop <- social_data %>%
    group_by(MutationRateSocial, GenomeLength, Time) %>%
    do(gnh_summary(.$MeanProducerProportion))

social_prop08 <- filter(social_prop, GenomeLength==0 | GenomeLength==8)

social_pres <- social_data %>%
    group_by(MutationRateSocial, GenomeLength, Source, Replicate) %>%
    summarise(Integral=sum(MeanProducerProportion)/(max(Time)-min(Time)))

social_pres08 <- filter(social_pres, GenomeLength==0 | GenomeLength==8)
```

```{r Proportion of Producers over Time}
p_social_prop <- ggplot(social_prop, aes(x=Time, y=Mean,
                                         color=as.factor(GenomeLength),
                                         fill=as.factor(GenomeLength),
                                   linetype=as.factor(MutationRateSocial))) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    facet_grid(MutationRateSocial ~ ., labeller=smu_labeller) +
    scale_linetype_manual(values=c('1e-05'='solid',
                                   '0'='dashed'),
                          name='Mutations at Social Allele', guide=FALSE) +
    scale_color_hue(name=label_genome_length, labels=label_genomelengths, 
                    guide=guide_legend(order=1)) +
    scale_fill_hue(guide=FALSE) +
    labs(x=label_time, y=label_producer_proportion) +
    theme_bdc_grey()
rescale_plot(p_social_prop, ratio=2.5)
#ggsave('../figures/all-social-proportion.png')
```

```{r Proportion of Producers over Time 08}
p_social_prop08 <- ggplot(social_prop08, aes(x=Time, y=Mean,
                                         color=as.factor(GenomeLength),
                                         fill=as.factor(GenomeLength),
                                   linetype=as.factor(MutationRateSocial))) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    scale_linetype_manual(values=c('1e-05'='solid',
                                   '0'='dashed'),
                          labels=c('1e-05'=expression(bold('0.00001')),
                                   '0'='0'),
                          name=label_socialmu,
                          guide=guide_legend(order=2, keywidth=0.9)) +
    scale_color_hue(name=label_genome_length, labels=label_genomelengths08,
                    guide=guide_legend(order=1)) +
    scale_fill_hue(guide=FALSE) +
    labs(x=label_time, y=label_producer_proportion) +
    theme_bdc_grey()
rescale_golden(p_social_prop08)
#ggsave_golden('../figures/08-social-proportion.png')
```


```{r Producer Presence}
p_social_presence <- ggplot(social_pres, aes(x=GenomeLength, y=Integral,
                                   color=as.factor(MutationRateSocial),
                                   shape=as.factor(MutationRateSocial))) +
    #geom_point(shape=1, alpha=0.06, position='identity') +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_continuous(breaks=unique(social_pres$GenomeLength),
                       labels=label_genomelengths) +
    scale_color_hue(name=label_socialmu) +
    scale_shape_manual(name=label_socialmu, 
                       values=c('0'=1, '1e-05'=16)) +
    labs(x=label_genome_length,
         y=label_producer_presence) +
    theme_bdc_grey(grid.y=FALSE)
rescale_golden(p_social_presence)
#ggsave_golden('../figures/all-social-presence.png')
```

```{r Producer Presence 08}
p_social_presence08 <- ggplot(social_pres08, aes(x=GenomeLength, y=Integral,
                                   color=as.factor(MutationRateSocial),
                                   shape=as.factor(MutationRateSocial))) +
    stat_summary(fun.y='mean', geom='line', aes(group=MutationRateSocial)) +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_continuous(breaks=unique(social_pres08$GenomeLength),
                       labels=label_genomelengths08) +
    scale_color_hue(name=label_socialmu) +
    scale_shape_manual(name=label_socialmu, 
                       values=c('0'=1, '1e-05'=16)) +
    labs(x=label_genome_length,
         y=label_producer_presence) +
    theme_bdc_grey(grid.y=FALSE)
rescale_plot(p_social_presence08, ratio=0.2)
#ggsave_golden('../figures/08-social-presence.png')
```

```{r Producer Presence Regression}
social <- filter(social_pres08, MutationRateSocial==1e-5)
nosocial <- filter(social_pres08, MutationRateSocial==0)

social_lm <- lm(Integral~GenomeLength, data=social)
nosocial_lm <- lm(Integral~GenomeLength, data=nosocial)

summary(social_lm)
summary(nosocial_lm)
```
