---
title: "Stress Mutation Rate"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
library(ggplot2bdc)
library(Hmisc)
library(magrittr)

load(file='../data/gnhdata.rda')
source('gnh_summary.R')
source('gnh_labels.R')
```

```{r subsetting}
stress_data <- gnhdata %>%
    filter(GenomeLength==8) %>%
    filter(PopulationStructure=='lattice, 25x25') %>%
    filter(FitnessDistribution=='uniform') %>%
    filter(MigrationRate==0.05) %>%
    filter(MutationRateSocial==1e-5) %>%
    filter(MutationRateAdaptation==1e-5) %>%
    filter(MinCarryingCapacity==800) %>%
    filter(MaxCarryingCapacity==2000)
```


```{r analysis}
stress_prop <- stress_data %>%
    group_by(MutationRateStress, Time) %>%
    do(gnh_summary(.$MeanProducerProportion))

stress_pres <- stress_data %>%
    group_by(MutationRateStress, Source, Replicate) %>%
    summarise(Integral=sum(MeanProducerProportion))
```

```{r Proportion of Producers over Time}
p_stress_prop <- ggplot(stress_prop, aes(x=Time, y=Mean,
                                         color=as.factor(MutationRateStress),
                                         fill=as.factor(MutationRateStress))) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_ribbon(aes(ymin=CL95_lower, ymax=CL95_upper), color=NA, alpha=0.2) +   
    geom_line() +
    scale_color_hue(name=label_stressmu, guide=guide_legend(order=1)) +
    scale_fill_hue(guide=FALSE) +
    labs(x=label_time, y=label_producer_proportion) +
    theme_bdc_grey()
rescale_golden(p_stress_prop)
#ggsave_golden('../figures/all-stress-proportion.png')
```

Note that these data reflect proportions after one cycle of growth

```{r Proportion of Producers After Stress}
stress_t0 <- filter(stress_data, Time==0)
p_stress_t0 <- ggplot(stress_t0, aes(x=MutationRateStress, y=MeanProducerProportion)) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    geom_point(shape=1, alpha=0.1) +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_log10(breaks=unique(stress_t0$MutationRateStress)) +
    scale_y_continuous(limits=c(0,1)) +
    labs(x=label_stressmu, y='Initial Producer Proportion') +
    theme_bdc_grey()
rescale_golden(p_stress_t0)
#ggsave_golden('../figures/all-stress-proportion-initial.png')
```

```{r Variation in Proportion of Producers After Stress}
stress_t0 <- filter(stress_data, Time==0)
p_stress_t0d <- ggplot(stress_t0, aes(x=MutationRateStress, y=MeanProducerProportion)) +
    geom_hline(yintercept=0.5, linetype='dotted', size=0.5, color='grey70') +   
    stat_summary(fun.y='sd', geom='point') +
    scale_x_log10(breaks=unique(stress_t0$MutationRateStress)) +
    labs(x=label_stressmu, y=label_producer_proportion_sd) +
    theme_bdc_grey()
rescale_golden(p_stress_t0d)
#ggsave_golden('../figures/all-stress-proportion-initial-sd.png')
```


```{r Producer Presence}
p_stress_presence <- ggplot(stress_pres, aes(x=MutationRateStress, y=Integral)) +
    geom_point(shape=1, alpha=0.06, position='identity') +
    stat_summary(fun.data='mean_cl_boot') +
    scale_x_log10(breaks=unique(stress_pres$MutationRateStress)) +
    labs(x=label_stressmu,
         y=sprintf('Producer Presence over %d Cycles',
                   max(stress_data$Time)-min(stress_data$Time))) +
    theme_bdc_grey(grid.y=FALSE)
rescale_golden(p_stress_presence)
#ggsave_golden('../figures/all-stress-presence.png')
```
